import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#012e40",
    paddingVertical: 20,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    marginBottom: 30,
    color: "#f3f3f3",
    textTransform: "uppercase",
    letterSpacing: 2,
    textAlign: "center",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  input: {
    width: "80%",
    height: 40,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 5,
    marginBottom: 10,
    paddingHorizontal: 10,
    color: "#F3F3F3",
  },
  button: {
    backgroundColor: "#026773",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    width: "80%",
    alignItems: "center",
  },
  buttonText: {
    color: "#F3F3F3",
    fontWeight: "bold",
  },
  containerHome: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#012e40",
  },
  buttonHome: {
    backgroundColor: "#026773",
    borderRadius: 10,
    marginTop: 10,
    width: "80%",
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    flexDirection: "row",
  },
  image: {
    width: 24,
    height: 24,
    tintColor: "#F3F3F3",
    marginRight: 10,
  },
  containerLista: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#012e40",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    width: "100%",
    paddingHorizontal: 20,
  },
  containerScroll: {
    padding: 20,
    backgroundColor: "#012e40",
    alignItems: "center",
    justifyContent: "center",
  },
  infoText: {
    color: "#F3F3F3",
    fontSize: 16,
    marginBottom: 10,
  },
  buttonCard: {
    backgroundColor: "#026773",
    padding: 0,
    borderRadius: 20,
    marginTop: 10,
    width: "100%",
    height: 200,
    marginBottom: 10,
    flexDirection: "row",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    overflow: "hidden",
  },
  headerText: {
    color: "#F3F3F3",
    fontSize: 24,
    fontWeight: "bold",
    marginBottom: 8,
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
  footerText: {
    color: "#F3F3F3",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 8,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    overflow: "hidden",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    textAlign: "center",
  },
  buttonCardHeader: {
    flex: 1,
    justifyContent: "space-between",
    width: "100%",
    paddingRight: 50,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    padding: 20,
  },
  buttonCardHeaderText: {
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "100%",
    paddingTop: 15,
  },
  buttonCardFooterText: {
    flexDirection: "row",
    justifyContent: "flex-start",
    alignItems: "center",
    width: "100%",
    padding: 10,
    marginTop: 15,
    gap: 10,
  },
  deleteIcon: {
    position: "absolute",
    top: 15,
    right: 15,
    backgroundColor: "rgba(229, 0, 0, 0.15)",
    padding: 12,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(229, 0, 0, 0.3)",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  priceTag: {
    position: "absolute",
    top: 15,
    right: 80,
    backgroundColor: "rgba(255, 255, 255, 0.15)",
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.2)",
  },
  priceText: {
    color: "#F3F3F3",
    fontSize: 18,
    fontWeight: "bold",
    textShadowColor: "rgba(0, 0, 0, 0.3)",
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 2,
  },
});
