import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#012e40",
  },
  title: {
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 20,
    color: "#f3f3f3",
  },
  input: {
    width: "80%",
    height: 40,
    borderWidth: 1,
    borderColor: "gray",
    borderRadius: 5,
    marginBottom: 10,
    paddingHorizontal: 10,
    color: "#F3F3F3",
  },
  button: {
    backgroundColor: "#026773",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    marginBottom: 10,
    width: "80%",
    alignItems: "center",
  },
  buttonText: {
    color: "#F3F3F3",
    fontWeight: "bold",
  },
  containerHome: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#012e40",
  },
  buttonHome: {
    backgroundColor: "#026773",
    borderRadius: 10,
    marginTop: 10,
    width: "80%",
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    flexDirection: "row",
  },
  image: {
    width: 24,
    height: 24,
    tintColor: "#F3F3F3",
    marginRight: 10,
  },
  containerLista: {
    flex: 1,
    alignItems: "center",
    backgroundColor: "#012e40",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    width: "100%",
  },
  containerScroll: {
    padding: 20,
    backgroundColor: "#012e40",
    alignItems: "center",
    justifyContent: "center",
  },
  infoText: {
    color: "#F3F3F3",
    fontSize: 16,
    marginBottom: 10,
  },
  buttonCard: {
    backgroundColor: "#026773",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    width: "100%",
    height: 150,
    marginBottom: 10,
    flexDirection: "row",
  },
  headerText: {
    color: "#F3F3F3",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  footerText: {
    color: "#F3F3F3",
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 10,
  },
  buttonCardHeader: {
    // flex: 1,
    justifyContent: "space-between",
    width: "100%",
  },
  buttonCardHeaderText: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    paddingTop: 20,
  },
  buttonCardFooterText: {	
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    padding: 10,
  },
  deleteIcon: {
    position: "absolute",
    top: 7,
    right: 7,
  },
});
